# Generated by Django 5.0.7 on 2024-07-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classroom',
            new_name='Classes',
        ),
    ]
